### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128) on setup

### ISSUE THREAD

**Issue by pExeen** [XenGi/pokey#8]
Hello when I run ```python setup.py``` I get this error:
```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    long_description=readme(),
  File "setup.py", line 8, in readme
    return fd.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
```
I am running python 3.6.4-2 on Arch Linux.

Thanks. :smile:

**Comment by XenGi** [comment]
You forgot to set your locale. Try to put something like `LANG=en_US.UTF-8` in `/etc/locale.conf`. That should do the trick.
